# Generated by Django 4.2.30 on 2026-04-23 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_caller'),
    ]

    operations = [
        migrations.AddField(
            model_name='caller',
            name='session_token',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
    ]
