# Generated by Django 4.2.30 on 2026-04-23 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_add_caller_session_token'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='caller',
            name='session_token',
        ),
        migrations.AlterField(
            model_name='contact',
            name='status',
            field=models.CharField(choices=[('new', 'New'), ('contacted', 'Contacted'), ('interested', 'Interested'), ('converted', 'Converted'), ('lost', 'Lost')], default='new', max_length=20),
        ),
    ]
